apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: henkaipan
  labels:
    app: postgres
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/henkaipan/postgres"
